00.PyTorch Fundamentals

resource- https://www.learnpytorch.io/00_pytorch_fundamentals/

In [ ]:
import torch
import  numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

2.2.1+cu121


## introduction to tensors.
### creating tensors

pytorch tensors are created using 'torch.Tensor()'

In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
# check dimensions
scalar.ndim

0

In [ ]:
# give item
scalar.item()

7

In [ ]:
# vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#MATRIX

MATRIX = torch.tensor([[7,8],
                      [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR
TENSOR= torch.tensor([[[1,2,3],
                      [4,5,6],
                       [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
TENSOR[0,1]

tensor([4, 5, 6])

In [ ]:
TENSOR[0,1,2]

tensor(6)

### random tensors

why random tensors?

random tensors are important because the way many networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent data

`start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [ ]:
#create a random tensor of size(3,4)

random_tensor = torch.rand(3, 4) # we can also put torch.rand(size=(3, 4)) it doesnt really matter by default
random_tensor

tensor([[0.9665, 0.6997, 0.2487, 0.5572],
        [0.7494, 0.3965, 0.4886, 0.6725],
        [0.7955, 0.6119, 0.4499, 0.4718]])

In [ ]:
random_tensor.ndim

2

In [ ]:
#create a random tensor with similar shape to an image tensor

random_image_size_tensor = torch.rand(size=(224,224,3)) #height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### zeros and ones

In [ ]:
#create a tensor with all zeross
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
#create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
random_tensor.dtype

torch.float32

### creating a range of tensors and tensors-like

In [ ]:
#use torch.arange()
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
one_to_ten= torch.arange(start=1, end =11, step= 1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#creating tensors like
ten_zeros = torch.zeros_like(input= one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes
**note:** tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:
1. tensors not right datatype
2. tensors not right shape
3. tensors not on the right device


In [ ]:
 float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                                dtype=None, #what datatype is the tensor (e.g. float 32 or float 16)
                                device=None, #what device is your tensor on (e.g. cpu or gpu)
                                requires_grad=False) #whether or not to track gradients with this tensors operations
 float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_32_tensor * float_16_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = torch.tensor([3, 6, 9], dtype =torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### getting information information from tensors (attributes)

1. tensors not right datatype - to do get datatype from a tensor, can use `tensor.dtype`
2. tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [ ]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.6815, 0.7846, 0.5729, 0.2923],
        [0.3042, 0.5914, 0.0131, 0.8842],
        [0.0353, 0.0595, 0.1686, 0.0162]])

In [ ]:
some_tensor.size(), some_tensor.shape
#both statements above result the same but size() is a function whereas shape is a method/attribute

(torch.Size([3, 4]), torch.Size([3, 4]))

In [ ]:
# find out details about some tensor
print(some_tensor)
print(f"Datatpe of tensor: {some_tensor.dtype}")
print(f"shape of tensor: {some_tensor.shape}")
print(f"device tensor is on: {some_tensor.device}")

tensor([[0.6815, 0.7846, 0.5729, 0.2923],
        [0.3042, 0.5914, 0.0131, 0.8842],
        [0.0353, 0.0595, 0.1686, 0.0162]])
Datatpe of tensor: torch.float32
shape of tensor: torch.Size([3, 4])
device tensor is on: cpu


### manipulating tensors (tensor operations)

tensor operations include:
* addition
* subtraction
* multiplication (element-wise)
* division
* matrix multiplication

In [ ]:
#create a tensor and add 10 to it

tensor = torch.tensor([1, 2, 3])
tensor + 10


tensor([11, 12, 13])

In [ ]:
#multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [ ]:
#subtract 10
tensor - 10

tensor([-9, -8, -7])

In [ ]:
# try out pytorch in-built functions

torch.mul(tensor, 10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor, 10)

tensor([11, 12, 13])

###matrix multiplication

two main ways to performing multiplication in neural networks and deep learning:

1. element-wise multiplication
2. matrix multiplication (dot product)

There are two main rules that performing matrix mutliplication needs to satisfy:
1. The **inner dimensions** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shape of the *outer dimensions**;
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`





In [ ]:
#element wise multiplication
print(tensor, "*", tensor)
print(f"equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
equals: tensor([1, 4, 9])


In [ ]:
#matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
#matrix multiplicaction by hand
1*1 + 2*2 + 3*3

14

In [ ]:
# the "@" symbol also stands for multiplication
tensor @ tensor

tensor(14)

In [ ]:
#the other way could be torch.mm() but it can only be done for MATRICES

In [ ]:
### one of the most common errors in deep learning: shape error

In [ ]:
torch.matmul(torch.rand([3,2]), torch.rand([2,3]))

tensor([[0.2391, 0.5662, 0.9190],
        [0.1361, 0.3488, 0.5551],
        [0.6947, 0.5538, 1.3507]])

In [ ]:
tensor_a = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_b = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])


In [ ]:
tensor_a.size(), tensor_b.size()

(torch.Size([3, 2]), torch.Size([3, 2]))

to fix our size issues, we can manipluate the shape of one of our tensors using a **transpose**

A **transpose** switches the axes or dimensions of a given tensor.

In [ ]:
tensor_b, tensor_b.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [ ]:
tensor_b.T, tensor_b.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [ ]:
torch.matmul(tensor_a, tensor_b.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [ ]:
print(f"original shapes: \ntensor_a = {tensor_a.shape},\ntensor_b = {tensor_b.shape}")
print(f"new shapes: \ntensor_a = {tensor_a.shape} (same as last), \ntensor_b.T = {tensor_b.T}")
print(f"multiplying: {tensor_a.shape} @ {tensor_b.shape} <- inner dimensions should match")
print("output:\n")
output = torch.matmul(tensor_a, tensor_b.T)
print(output)
print(f"output shape: {output.shape}")

original shapes: 
tensor_a = torch.Size([3, 2]),
tensor_b = torch.Size([3, 2])
new shapes: 
tensor_a = torch.Size([3, 2]) (same as last), 
tensor_b.T = tensor([[ 7,  8,  9],
        [10, 11, 12]])
multiplying: torch.Size([3, 2]) @ torch.Size([3, 2]) <- inner dimensions should match
output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])
output shape: torch.Size([3, 3])


##finding the max, min, mean, sum, etc (tensor aggregation)

In [ ]:
#crate a tensor
x = torch.arange(1,100,10)
x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [ ]:
#find the min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [ ]:
#find the max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [ ]:
#find mean
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

#the torch.mean() function requires a tensor of float32 datatype to work
#mean can not be calculated off of integer values thats why we need to convert it into flaot or long

(tensor(46.), tensor(46.))

In [ ]:
#find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

## finding the positional min and max

In [ ]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
#find the position in tensor that has minimum value with argmin() -> returns index position of target tensor where minimum value occurs
x.argmin()

tensor(0)

In [ ]:
x[0]

tensor(1)

In [ ]:
x.argmax()

tensor(9)

In [ ]:
x[9]

tensor(91)

## reshapnig, stacking, squeezing and unsqueezing tensors

* reshaping - reshapes an input tensor to a defind shape
* view - return a view of an input tensor of certain shape but keep the asme memory as the original tensor
* stacking -  combine multiple tensors on top of each other (vstack),  or side by side (hstack)
* squeeze - removes all `1` demonsions from a tensor
* unsqueeze - add a `1` dimension to a taget tensor
* permute - return a view of the input with dimensions permuted (swapped) in a certain way

In [ ]:
# lets creat a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# change the view
z = x.view(9, 1)
z , z.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [ ]:
# changing z changes x (because a view of a tensor shares the same as the original)
z[:, 0]
z , x

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [ ]:
#torch.squeeze() - removes all single dimesions from a target tensor
print(f"previous tensor: {x_reshaped}")
print(f"previous shape: {x_reshaped.shape}")

#remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"new tensor: {x_squeezed}")
print(f"new shape: {x_squeezed.shape}")

previous tensor: tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
previous shape: torch.Size([1, 9])
new tensor: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
new shape: torch.Size([9])


In [ ]:
#torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
print(f"previous tensor: {x_squeezed}")
print(f"previous shape: {x_squeezed.shape}")

#add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim= 0)
print(f"new tensor: {x_unsqueezed}")
print(f"new shape: {x_unsqueezed.shape}")


previous tensor: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
previous shape: torch.Size([9])
new tensor: tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
new shape: torch.Size([1, 9])


In [ ]:
# torch.permute() - rearranges the dimensions of a target tensor in a specified order
# mostly used in images

x_original = torch.rand(size = (224, 224, 3)) #height, width, color_channels

#permute the original tensor to rearrange the axais (or dim) order
x_permuted = x_original.permute(2, 0, 1) #shifts axis 0->1, 1->2, 2->0

print(f"previous shape: {x_original.shape}")
print(f"new shape: {x_permuted.shape}") #(color_channel, height, width))

previous shape: torch.Size([224, 224, 3])
new shape: torch.Size([3, 224, 224])


In [ ]:
x_original[0,0,0] = 123456
x_original[0,0,0], x_permuted[0,0,0]

(tensor(123456.), tensor(123456.))

##indexing (selecting data from tensors)
indexing with PyTorch is similar to indexing with NumPy

In [ ]:
#create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
#lets index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
#lets nidex on the middle brack(dim=0)
x[0][0]

tensor([1, 2, 3])

In [ ]:
#lets index on the most inner bracker (last dimension)
x[0][2][2]

tensor(9)

In [ ]:
#you can also use ":" to select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [ ]:
#get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
#get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [ ]:
#get index 0 of 0th and 1st dimensino and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [ ]:
#index on x to return 9
x[0,2,2]

tensor(9)

#PyTorch tensors & NumPy

NumPy is a popular scientific python numerical computing library

and because of this, pytoech has functionality to interact with it

* data in NumPy, want in PyTorch tensor -> `torch.fromnumpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [ ]:
#numpy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) #warnig: when converting form numpy -> pytorch, pytorch refelcts numpy's default datatype of float64 unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
array.dtype

dtype('float64')

In [ ]:
torch.arange(1.0, 8.0).dtype

torch.float32

In [ ]:
#change the value of array (what will this do to the tensor?)

array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
#tensor to numpy array

tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
#change the tensor, keep the array

tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## reproducibility (trying to take random out of random)

in short how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again...`

to reduce the randomness in neural networks and pytorch comes the concept of a **random seed**.

essentially what the random seed does is "flavour" the randomness

In [ ]:
import torch

random_tensor_a = torch.rand(3, 4)
random_tensor_b = torch.rand(3, 4)

print(f"tensor A: \n{random_tensor_a}\n")
print(f"tensor B: \n{random_tensor_b}\n")
print(f"does tensor A and Tensor B match(anywhere)??")
random_tensor_a == random_tensor_b

tensor A: 
tensor([[0.3108, 0.0338, 0.0060, 0.0706],
        [0.4796, 0.0484, 0.5239, 0.0890],
        [0.6856, 0.2318, 0.4382, 0.5908]])

tensor B: 
tensor([[0.7197, 0.0424, 0.8847, 0.8740],
        [0.1750, 0.1172, 0.9098, 0.0484],
        [0.2720, 0.0681, 0.3047, 0.3716]])

does tensor A and Tensor B match(anywhere)??


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [ ]:
import torch
import random

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_c = torch.rand(3, 4)

torch.random.manual_seed(RANDOM_SEED)
random_tensor_d = torch.rand(3, 4)

print(f"tensor C: \n{random_tensor_c}\n")
print(f"tensor D: \n{random_tensor_d}\n")
print(f"does tensor C and Tensor D match(anywhere)??")
random_tensor_c == random_tensor_d


tensor C: 
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

tensor D: 
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

does tensor C and Tensor D match(anywhere)??


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [ ]:
##  Running tensors and PyTorch objects on the GPUs (and making faster computations)